//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRPO4KURS_Stetskiy_Sirotkin
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipper
    {
        public int Shipper_id { get; set; }
        public int Shipment_id { get; set; }
        public string Company_Name { get; set; }
        public string Phone { get; set; }
    
        public virtual Shipment Shipment { get; set; }
    }
}
